name: Deploy to production
on:
  push:
    branches: [ production ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: Write SSH key
        run: |
          printf '%s' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: SSH into server and deploy
        run: |
            ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@13.50.233.89 << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use node

            cd CollabBoard/
            git pull origin production
            npm install -g pnpm
            pnpm install
            pnpm run build
            pm2 restart http-server
            pm2 restart web
            pm2 restart ws-backend
            EOF





         
