name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: Write SSH key
        run: |
          printf '%s' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: SSH into server and deploy
        run: |
            ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@13.51.252.133 << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use node

            cd CollabBoard/
            git pull origin main
            npm install -g pnpm
            pnpm install
            pnpm run build
            pm2 restart fe-sever
            pm2 restart http-sever
            pm2 restart ws-sever
            EOF





         
